resolver: lts-8.4
packages:
  - '.'
  - location: '../hjsonschema'
    extra-dep: true

extra-deps:
  # - hjsonschema-1.5.0.0
 - hjsonpointer-1.1.0.1
 - aeson-1.1.0.0

nix:
  enable: true
  shell-file: shell.nix
