resolver: lts-8.4
packages:
  - '.'
  - location: '../hjsonschema'
    extra-dep: true

extra-deps:
 - hjsonschema-1.6.2
 - hjsonpointer-1.1.1
 - aeson-1.2.0.0

nix:
  enable: true
  shell-file: shell.nix
